import { getDictionary, isLocale, type Locale } from "@/lib/i18n";
import type { FinanceReportsCopy } from "@/modules/finance/contracts/finance-reports-copy.contract";

function adminCopy(locale: string) {
  const resolvedLocale: Locale = isLocale(locale) ? locale : "tr";
  return getDictionary(resolvedLocale).admin as Record<string, string>;
}

export function resolveFinanceReportsCopy(locale: string): FinanceReportsCopy {
  const resolvedLocale: Locale = isLocale(locale) ? locale : "tr";
  const admin = adminCopy(locale);

  return {
    notSpecified: getDictionary(resolvedLocale).common.notSpecified as string,
    openCta: admin.financeReportsOpenCta,
    variantJoiner: admin.financeReportsVariantJoiner,
    agingBuckets: [
      { id: "0-7", label: admin.financeReportsAgingBucket0_7, minDays: 0, maxDays: 7 },
      { id: "8-30", label: admin.financeReportsAgingBucket8_30, minDays: 8, maxDays: 30 },
      { id: "31-60", label: admin.financeReportsAgingBucket31_60, minDays: 31, maxDays: 60 },
      { id: "61-plus", label: admin.financeReportsAgingBucket61Plus, minDays: 61, maxDays: null },
    ],
    overview: {
      netBalanceLabel: admin.financeReportsOverviewNetBalanceLabel,
      netBalanceHint: admin.financeReportsOverviewNetBalanceHint,
      bankBalanceLabel: admin.financeReportsOverviewBankBalanceLabel,
      bankBalanceHintSuffix: admin.financeReportsOverviewBankBalanceHintSuffix,
      recordedNetCashLabel: admin.financeReportsOverviewRecordedNetCashLabel,
      recordedNetCashHintSuffix: admin.financeReportsOverviewRecordedNetCashHintSuffix,
      cashGapLabel: admin.financeReportsOverviewCashGapLabel,
      cashGapHint: admin.financeReportsOverviewCashGapHint,
      cardAgingTitle: admin.financeReportsCardAgingTitle,
      cardAgingDescription: admin.financeReportsCardAgingDescription,
      cardCashflowTitle: admin.financeReportsCardCashflowTitle,
      cardCashflowDescription: admin.financeReportsCardCashflowDescription,
      cardStockTitle: admin.financeReportsCardStockTitle,
      cardStockDescription: admin.financeReportsCardStockDescription,
      cardPerformanceTitle: admin.financeReportsCardPerformanceTitle,
      cardPerformanceDescription: admin.financeReportsCardPerformanceDescription,
      cardIncomeExpenseTitle: admin.financeReportsCardIncomeExpenseTitle,
      cardIncomeExpenseDescription: admin.financeReportsCardIncomeExpenseDescription,
      cardBankCashTitle: admin.financeReportsCardBankCashTitle,
      cardBankCashDescription: admin.financeReportsCardBankCashDescription,
      cardVatSummaryTitle: admin.financeReportsCardVatSummaryTitle,
      cardVatSummaryDescription: admin.financeReportsCardVatSummaryDescription,
      cardTrialBalanceTitle: admin.financeReportsCardTrialBalanceTitle,
      cardTrialBalanceDescription: admin.financeReportsCardTrialBalanceDescription,
    },
    performance: {
      title: admin.financeReportsPerformanceTitle,
      description: admin.financeReportsPerformanceDescription,
      collectionCompletionLabel: admin.financeReportsPerformanceCollectionCompletionLabel,
      paymentCompletionLabel: admin.financeReportsPerformancePaymentCompletionLabel,
      openReceivableLabel: admin.financeReportsPerformanceOpenReceivableLabel,
      openPayableLabel: admin.financeReportsPerformanceOpenPayableLabel,
      recordedCollectionHintSuffix: admin.financeReportsPerformanceRecordedCollectionHintSuffix,
      recordedPaymentHintSuffix: admin.financeReportsPerformanceRecordedPaymentHintSuffix,
      pendingOrdersHintSuffix: admin.financeReportsPerformancePendingOrdersHintSuffix,
      suppliersHintSuffix: admin.financeReportsPerformanceSuppliersHintSuffix,
      collectionRowRecordSuffix: admin.financeReportsPerformanceCollectionRowRecordSuffix,
      paymentRowRecordSuffix: admin.financeReportsPerformancePaymentRowRecordSuffix,
      paymentRowDocumentSuffix: admin.financeReportsPerformancePaymentRowDocumentSuffix,
    },
    aging: {
      title: admin.financeReportsAgingTitle,
      description: admin.financeReportsAgingDescription,
      totalReceivableLabel: admin.financeReportsAgingTotalReceivableLabel,
      totalPayableLabel: admin.financeReportsAgingTotalPayableLabel,
      netPositionLabel: admin.financeReportsAgingNetPositionLabel,
      netPositionHint: admin.financeReportsAgingNetPositionHint,
      openOrdersHintSuffix: admin.financeReportsAgingOpenOrdersHintSuffix,
      supplierSummaryHintSuffix: admin.financeReportsAgingSupplierSummaryHintSuffix,
      rowSupportingBase: admin.financeReportsAgingRowSupportingBase,
      rowSupportingWithVariantsPrefix: admin.financeReportsAgingRowSupportingWithVariantsPrefix,
      tableTitle: admin.financeReportsAgingTableTitle,
      tableDescription: admin.financeReportsAgingTableDescription,
    },
    cashflow: {
      title: admin.financeReportsCashflowTitle,
      description: admin.financeReportsCashflowDescription,
      expectedNetLabel: admin.financeReportsCashflowExpectedNetLabel,
      expectedNetHint: admin.financeReportsCashflowExpectedNetHint,
      recordedNetLabel: admin.financeReportsCashflowRecordedNetLabel,
      recordedNetHint: admin.financeReportsCashflowRecordedNetHint,
      actualBalanceLabel: admin.financeReportsCashflowActualBalanceLabel,
      actualBalanceHintSuffix: admin.financeReportsCashflowActualBalanceHintSuffix,
      coverageGapLabel: admin.financeReportsCashflowCoverageGapLabel,
      coverageGapHint: admin.financeReportsCashflowCoverageGapHint,
      expectedCollectionLabel: admin.financeReportsCashflowExpectedCollectionLabel,
      expectedCollectionSupporting: admin.financeReportsCashflowExpectedCollectionSupporting,
      expectedPaymentLabel: admin.financeReportsCashflowExpectedPaymentLabel,
      expectedPaymentSupportingBase: admin.financeReportsCashflowExpectedPaymentSupportingBase,
      expectedPaymentSupportingWithVariantsPrefix: admin.financeReportsCashflowExpectedPaymentSupportingWithVariantsPrefix,
      recordedCollectionLabel: admin.financeReportsCashflowRecordedCollectionLabel,
      recordedCollectionHintSuffix: admin.financeReportsCashflowRecordedCollectionHintSuffix,
      recordedPaymentLabel: admin.financeReportsCashflowRecordedPaymentLabel,
      recordedPaymentHintSuffix: admin.financeReportsCashflowRecordedPaymentHintSuffix,
      cashAccountType: admin.financeReportsCashflowCashAccountType,
      bankAccountType: admin.financeReportsCashflowBankAccountType,
      movementsHintSuffix: admin.financeReportsCashflowMovementsHintSuffix,
      tableTitle: admin.financeReportsCashflowTableTitle,
      tableDescription: admin.financeReportsCashflowTableDescription,
      paymentAmountColumn: admin.financeReportsCashflowPaymentAmountColumn,
      periodRecordedNetHint: admin.financeReportsCashflowPeriodRecordedNetHint,
    },
    bankCash: {
      title: admin.financeReportsBankCashTitle,
      description: admin.financeReportsBankCashDescription,
      totalIncomingLabel: admin.financeReportsBankCashTotalIncomingLabel,
      totalOutgoingLabel: admin.financeReportsBankCashTotalOutgoingLabel,
      netLabel: admin.financeReportsBankCashNetLabel,
      netHint: admin.financeReportsBankCashNetHint,
      movementCountLabel: admin.financeReportsBankCashMovementCountLabel,
      movementCountHintSuffix: admin.financeReportsBankCashMovementCountHintSuffix,
      tableTitle: admin.financeReportsBankCashTableTitle,
      tableDescription: admin.financeReportsBankCashTableDescription,
      colAccount: admin.financeReportsBankCashColAccount,
      colDate: admin.financeReportsBankCashColDate,
      colTitle: admin.financeReportsBankCashColTitle,
      colDirection: admin.financeReportsBankCashColDirection,
      colAmount: admin.financeReportsBankCashColAmount,
      colCategory: admin.financeReportsBankCashColCategory,
      directionIncoming: admin.financeReportsBankCashDirectionIncoming,
      directionOutgoing: admin.financeReportsBankCashDirectionOutgoing,
      directionTransfer: admin.financeReportsBankCashDirectionTransfer,
    },
    stockValue: {
      title: admin.financeReportsStockTitle,
      description: admin.financeReportsStockDescription,
      totalValueLabel: admin.financeReportsStockTotalValueLabel,
      totalValueHintSuffix: admin.financeReportsStockTotalValueHintSuffix,
      totalUnitsLabel: admin.financeReportsStockTotalUnitsLabel,
      totalUnitsHint: admin.financeReportsStockTotalUnitsHint,
      inStockCountLabel: admin.financeReportsStockInStockCountLabel,
      inStockCountHint: admin.financeReportsStockInStockCountHint,
      rowMovementInBucketSuffix: admin.financeReportsStockRowMovementInBucketSuffix,
      tableTitle: admin.financeReportsStockTableTitle,
      tableDescription: admin.financeReportsStockTableDescription,
      colPurchasePrice: admin.financeReportsStockColPurchasePrice,
      colAverageCost: admin.financeReportsStockColAverageCost,
      colStockValue: admin.financeReportsStockColStockValue,
      colLastOrder: admin.financeReportsStockColLastOrder,
    },
    columns: {
      agingBucket: admin.financeReportsColAgingBucket,
      supplier: admin.financeReportsColSupplier,
      document: admin.financeReportsColDocument,
      issueDate: admin.financeReportsColIssueDate,
      product: admin.financeReportsColProduct,
      variant: admin.financeReportsColVariant,
      sku: admin.financeReportsColSku,
      quantity: admin.financeReportsColQuantity,
      unitCost: admin.financeReportsColUnitCost,
      lineTotal: admin.financeReportsColLineTotal,
      name: admin.financeReportsColName,
      stock: admin.financeReportsColStock,
    },
    incomeExpense: {
      title: admin.financeReportsIncomeExpenseTitle,
      description: admin.financeReportsIncomeExpenseDescription,
      dateRangeHint: admin.financeReportsIncomeExpenseDateRangeHint,
      totalIncomeLabel: admin.financeReportsIncomeExpenseTotalIncomeLabel,
      totalExpenseLabel: admin.financeReportsIncomeExpenseTotalExpenseLabel,
      netLabel: admin.financeReportsIncomeExpenseNetLabel,
      netHint: admin.financeReportsIncomeExpenseNetHint,
      movementCountLabel: admin.financeReportsIncomeExpenseMovementCountLabel,
      movementCountHintSuffix: admin.financeReportsIncomeExpenseMovementCountHintSuffix,
      tableTitle: admin.financeReportsIncomeExpenseTableTitle,
      tableDescription: admin.financeReportsIncomeExpenseTableDescription,
      colCategory: admin.financeReportsIncomeExpenseColCategory,
      colIncome: admin.financeReportsIncomeExpenseColIncome,
      colExpense: admin.financeReportsIncomeExpenseColExpense,
      colNet: admin.financeReportsIncomeExpenseColNet,
      colMovements: admin.financeReportsIncomeExpenseColMovements,
      categoryUnspecified: admin.financeReportsIncomeExpenseCategoryUnspecified,
      categoryGeneralIncome: admin.financeReportsIncomeExpenseCategoryGeneralIncome,
      categoryGeneralExpense: admin.financeReportsIncomeExpenseCategoryGeneralExpense,
      categoryMarketplaceCommission: admin.financeReportsIncomeExpenseCategoryMarketplaceCommission,
      categoryShippingExpense: admin.financeReportsIncomeExpenseCategoryShippingExpense,
      categoryServiceFee: admin.financeReportsIncomeExpenseCategoryServiceFee,
      categoryRefund: admin.financeReportsIncomeExpenseCategoryRefund,
      categoryTransfer: admin.financeReportsIncomeExpenseCategoryTransfer,
    },
    vatSummary: {
      title: admin.financeReportsVatSummaryTitle,
      description: admin.financeReportsVatSummaryDescription,
      outputTaxLabel: admin.financeReportsVatSummaryOutputTaxLabel,
      inputTaxLabel: admin.financeReportsVatSummaryInputTaxLabel,
      netTaxLabel: admin.financeReportsVatSummaryNetTaxLabel,
      netTaxHint: admin.financeReportsVatSummaryNetTaxHint,
      documentCountLabel: admin.financeReportsVatSummaryDocumentCountLabel,
      documentCountHintSuffix: admin.financeReportsVatSummaryDocumentCountHintSuffix,
      tableTitle: admin.financeReportsVatSummaryTableTitle,
      tableDescription: admin.financeReportsVatSummaryTableDescription,
      colDocument: admin.financeReportsVatSummaryColDocument,
      colDocumentType: admin.financeReportsVatSummaryColDocumentType,
      colCounterparty: admin.financeReportsVatSummaryColCounterparty,
      colIssueDate: admin.financeReportsVatSummaryColIssueDate,
      colDirection: admin.financeReportsVatSummaryColDirection,
      colTaxBase: admin.financeReportsVatSummaryColTaxBase,
      colTaxAmount: admin.financeReportsVatSummaryColTaxAmount,
      colTotal: admin.financeReportsVatSummaryColTotal,
      colVatRate: admin.financeReportsVatSummaryColVatRate,
      directionOutput: admin.financeReportsVatSummaryDirectionOutput,
      directionInput: admin.financeReportsVatSummaryDirectionInput,
      documentTypeSales: admin.financeReportsVatSummaryDocumentTypeSales,
      documentTypePurchase: admin.financeReportsVatSummaryDocumentTypePurchase,
      rateUnspecified: admin.financeReportsVatSummaryRateUnspecified,
      rateBucketRowSuffix: admin.financeReportsVatSummaryRateBucketRowSuffix,
    },
    trialBalance: {
      title: admin.financeReportsTrialBalanceTitle,
      description: admin.financeReportsTrialBalanceDescription,
      totalDebitLabel: admin.financeReportsTrialBalanceTotalDebitLabel,
      totalCreditLabel: admin.financeReportsTrialBalanceTotalCreditLabel,
      balanceCheckLabel: admin.financeReportsTrialBalanceBalanceCheckLabel,
      balanceOkHint: admin.financeReportsTrialBalanceBalanceOkHint,
      balanceGapHint: admin.financeReportsTrialBalanceBalanceGapHint,
      accountCountLabel: admin.financeReportsTrialBalanceAccountCountLabel,
      accountCountHint: admin.financeReportsTrialBalanceAccountCountHint,
      tableTitle: admin.financeReportsTrialBalanceTableTitle,
      tableDescription: admin.financeReportsTrialBalanceTableDescription,
      colAccountCode: admin.financeReportsTrialBalanceColAccountCode,
      colAccountName: admin.financeReportsTrialBalanceColAccountName,
      colCategory: admin.financeReportsTrialBalanceColCategory,
      colDebit: admin.financeReportsTrialBalanceColDebit,
      colCredit: admin.financeReportsTrialBalanceColCredit,
      colBalance: admin.financeReportsTrialBalanceColBalance,
    },
    dateRange: {
      fromLabel: admin.financeReportsDateRangeFromLabel,
      toLabel: admin.financeReportsDateRangeToLabel,
      applyLabel: admin.financeReportsDateRangeApplyLabel,
      defaultMonthHint: admin.financeReportsDateRangeDefaultMonthHint,
      mobileToggleLabel: admin.financeReportsDateRangeMobileToggleLabel,
      exportCsvLabel: admin.financeReportsDateRangeExportCsvLabel,
    },
  };
}
