export const RBAC_PERMISSIONS = [
  { key: "admin.access", module: "admin", action: "access", menuKey: null, name: "Admin panele erişim" },
  { key: "users.manage", module: "users", action: "manage", menuKey: "users", name: "Kullanıcı ve rol yönetimi" },
  { key: "audit.read", module: "audit", action: "read", menuKey: "audit-logs", name: "İşlem kayıtlarını görüntüleme" },
  { key: "audit.export", module: "audit", action: "export", menuKey: "audit-logs", name: "İşlem kayıtlarını dışa aktarma" },
  { key: "products.read", module: "products", action: "read", menuKey: "products", name: "Ürünleri görüntüleme" },
  { key: "products.manage", module: "products", action: "manage", menuKey: "products", name: "Ürünleri yönetme" },
  { key: "productQuestions.read", module: "productQuestions", action: "read", menuKey: "product-questions", name: "Ürün sorularını görüntüleme" },
  { key: "productQuestions.manage", module: "productQuestions", action: "manage", menuKey: "product-questions", name: "Ürün sorularını yanıtlama/yönetme" },
  { key: "categories.manage", module: "categories", action: "manage", menuKey: "categories", name: "Kategorileri yönetme" },
  { key: "storefront.manage", module: "storefront", action: "manage", menuKey: "storefront", name: "Vitrini yönetme" },
  { key: "productAttributes.manage", module: "productAttributes", action: "manage", menuKey: "product-attributes", name: "Ürün özelliklerini yönetme" },
  { key: "brands.manage", module: "brands", action: "manage", menuKey: "brands", name: "Markaları yönetme" },
  { key: "orders.read", module: "orders", action: "read", menuKey: "orders", name: "Siparişleri görüntüleme" },
  { key: "orders.manage", module: "orders", action: "manage", menuKey: "orders", name: "Siparişleri yönetme" },
  { key: "ordersShippingReport.read", module: "orders", action: "shippingReportRead", menuKey: "orders-shipping-report", name: "Kargo firması raporunu görüntüleme" },
  { key: "inventory.read", module: "inventory", action: "read", menuKey: "inventory", name: "Stokları görüntüleme" },
  { key: "inventory.manage", module: "inventory", action: "manage", menuKey: "inventory", name: "Stokları yönetme" },
  { key: "inventoryProducts.read", module: "inventory", action: "productsRead", menuKey: "inventory-products", name: "Ürün stoklarını görüntüleme" },
  { key: "inventoryTransactions.read", module: "inventory", action: "transactionsRead", menuKey: "inventory-transactions", name: "Stok hareketlerini görüntüleme" },
  { key: "inventoryExports.read", module: "inventory", action: "exportsRead", menuKey: "inventory-exports", name: "Stok dışa aktarım geçmişini görüntüleme" },
  { key: "inventoryExternalEvents.read", module: "inventory", action: "externalEventsRead", menuKey: "inventory-external-events", name: "Harici stok eventlerini görüntüleme" },
  { key: "inventoryQuickActions.manage", module: "inventory", action: "quickActionsManage", menuKey: "inventory-quick-actions", name: "Hızlı barkod işlemlerini yönetme" },
  { key: "inventoryCounts.manage", module: "inventory", action: "countsManage", menuKey: "inventory-counts", name: "Stok sayımını yönetme" },
  { key: "warehouses.manage", module: "warehouses", action: "manage", menuKey: "inventory-warehouses", name: "Depoları yönetme" },
  { key: "inventoryExternalEvents.manage", module: "inventory", action: "externalEventsManage", menuKey: "inventory-external-events", name: "Harici stok eventlerini yönetme" },
  { key: "documents.read", module: "documents", action: "read", menuKey: "documents", name: "Belgeleri görüntüleme" },
  { key: "documents.manage", module: "documents", action: "manage", menuKey: "documents", name: "Belgeleri yönetme" },
  { key: "documentsPendingInvoices.manage", module: "documents", action: "pendingInvoicesManage", menuKey: "documents-pending-invoices", name: "Bekleyen faturaları yönetme" },
  { key: "documentsProviders.manage", module: "documents", action: "providersManage", menuKey: "documents-providers", name: "Belge sağlayıcılarını yönetme" },
  { key: "documentsWebhooks.manage", module: "documents", action: "webhooksManage", menuKey: "documents-webhooks", name: "Belge webhooklarını yönetme" },
  { key: "incomingInvoices.read", module: "incomingInvoices", action: "read", menuKey: "incoming-invoices", name: "Gelen faturaları görüntüleme" },
  { key: "incomingInvoices.manage", module: "incomingInvoices", action: "manage", menuKey: "incoming-invoices", name: "Gelen faturaları yönetme" },
  { key: "finance.read", module: "finance", action: "read", menuKey: "finance", name: "Finansı görüntüleme" },
  { key: "finance.manage", module: "finance", action: "manage", menuKey: "finance", name: "Finansı yönetme" },
  { key: "financePayables.read", module: "finance", action: "payablesRead", menuKey: "finance-payables", name: "Tedarikçi borçlarını görüntüleme" },
  { key: "financeReceivables.read", module: "finance", action: "receivablesRead", menuKey: "finance-receivables", name: "Müşteri alacaklarını görüntüleme" },
  { key: "financeReports.read", module: "finance", action: "reportsRead", menuKey: "finance-reports", name: "Finans raporlarını görüntüleme" },
  { key: "financeTrialBalance.read", module: "finance", action: "trialBalanceRead", menuKey: "finance-trial-balance", name: "Mizanı görüntüleme" },
  { key: "financeLedgerEntries.read", module: "finance", action: "ledgerEntriesRead", menuKey: "finance-ledger-entries", name: "Defter kayıtlarını görüntüleme" },
  { key: "financeAccounts.read", module: "finance", action: "accountsRead", menuKey: "finance-accounts", name: "Hesapları görüntüleme" },
  { key: "cari.manage", module: "cari", action: "manage", menuKey: "cari", name: "Carileri yönetme" },
  { key: "financeCollections.manage", module: "finance", action: "collectionsManage", menuKey: "finance-collections", name: "Tahsilatları yönetme" },
  { key: "financePayments.manage", module: "finance", action: "paymentsManage", menuKey: "finance-payments", name: "Ödemeleri yönetme" },
  { key: "financeBankCash.manage", module: "finance", action: "bankCashManage", menuKey: "finance-bank-cash", name: "Banka ve kasayı yönetme" },
  { key: "financeBankReconciliation.manage", module: "finance", action: "bankReconciliationManage", menuKey: "finance-bank-reconciliation", name: "Banka mutabakatını yönetme" },
  { key: "financeInstruments.manage", module: "finance", action: "instrumentsManage", menuKey: "finance-instruments", name: "Kıymetli evrakları yönetme" },
  { key: "financeTransactions.manage", module: "finance", action: "transactionsManage", menuKey: "finance-transactions", name: "Finans işlemlerini yönetme" },
  { key: "finance.audit.read", module: "finance", action: "audit_read", menuKey: "finance-exports", name: "Mali müşavir export paketi" },
  { key: "integrations.read", module: "integrations", action: "read", menuKey: "integrations", name: "Entegrasyonları görüntüleme" },
  { key: "integrations.manage", module: "integrations", action: "manage", menuKey: "integrations", name: "Entegrasyonları yönetme" },
  { key: "integrationsTrendyol.manage", module: "integrations", action: "trendyolManage", menuKey: "integrations-trendyol", name: "Trendyol entegrasyonunu yönetme" },
  { key: "integrationsN11.manage", module: "integrations", action: "n11Manage", menuKey: "integrations-n11", name: "N11 entegrasyonunu yönetme" },
  { key: "integrationsPazarama.manage", module: "integrations", action: "pazaramaManage", menuKey: "integrations-pazarama", name: "Pazarama entegrasyonunu yönetme" },
  { key: "integrationsHepsiburada.manage", module: "integrations", action: "hepsiburadaManage", menuKey: "integrations-hepsiburada", name: "Hepsiburada entegrasyonunu yönetme" },
  { key: "customers.manage", module: "users", action: "customersManage", menuKey: "customers", name: "Müşteri kullanıcılarını yönetme" },
  { key: "systemUsers.manage", module: "users", action: "systemUsersManage", menuKey: "system-users", name: "Sistem kullanıcılarını yönetme" },
  { key: "roles.manage", module: "users", action: "rolesManage", menuKey: "roles", name: "Rolleri yönetme" },
] as const;

export type PermissionKey = (typeof RBAC_PERMISSIONS)[number]["key"];

export const ALL_PERMISSION_KEYS = RBAC_PERMISSIONS.map((permission) => permission.key) as PermissionKey[];

export const RBAC_SYSTEM_ROLES = [
  {
    key: "super-admin",
    name: "Süper Yönetici",
    description: "Beemmb genelindeki tüm menü, API ve güvenlik yönetimi yetkilerine sahiptir.",
    permissions: ALL_PERMISSION_KEYS,
    legacyRoles: ["ADMIN"],
  },
  {
    key: "operation",
    name: "Operasyon",
    description: "Ürün, sipariş, stok ve belge süreçlerini günlük operasyon için yönetir.",
    permissions: [
      "admin.access",
      "products.read",
      "products.manage",
      "productQuestions.read",
      "productQuestions.manage",
      "categories.manage",
      "storefront.manage",
      "productAttributes.manage",
      "brands.manage",
      "orders.read",
      "orders.manage",
      "ordersShippingReport.read",
      "inventory.read",
      "inventory.manage",
      "inventoryProducts.read",
      "inventoryTransactions.read",
      "inventoryExports.read",
      "inventoryExternalEvents.read",
      "inventoryQuickActions.manage",
      "inventoryCounts.manage",
      "warehouses.manage",
      "inventoryExternalEvents.manage",
      "documents.read",
      "documents.manage",
      "documentsPendingInvoices.manage",
      "documentsProviders.manage",
      "documentsWebhooks.manage",
      "incomingInvoices.read",
      "incomingInvoices.manage",
      "integrations.read",
    ],
    legacyRoles: ["EDITOR"],
  },
  {
    key: "auditor",
    name: "Denetçi",
    description: "İşlem kayıtları ve kritik kayıtları salt okunur izler.",
    permissions: [
      "admin.access",
      "audit.read",
      "products.read",
      "productQuestions.read",
      "orders.read",
      "ordersShippingReport.read",
      "inventory.read",
      "inventoryProducts.read",
      "inventoryTransactions.read",
      "inventoryExports.read",
      "inventoryExternalEvents.read",
      "documents.read",
      "incomingInvoices.read",
      "finance.read",
      "financePayables.read",
      "financeReceivables.read",
      "financeReports.read",
      "financeTrialBalance.read",
      "financeLedgerEntries.read",
      "financeAccounts.read",
      "integrations.read",
    ],
    legacyRoles: [],
  },
  {
    key: "finance",
    name: "Finans",
    description: "Tahsilat, ödeme, cari ve finans raporlarını yönetir.",
    permissions: [
      "admin.access",
      "orders.read",
      "ordersShippingReport.read",
      "documents.read",
      "incomingInvoices.read",
      "incomingInvoices.manage",
      "finance.read",
      "financePayables.read",
      "financeReceivables.read",
      "financeReports.read",
      "financeTrialBalance.read",
      "financeLedgerEntries.read",
      "finance.manage",
      "financeAccounts.read",
      "cari.manage",
      "financeCollections.manage",
      "financePayments.manage",
      "financeBankCash.manage",
      "financeBankReconciliation.manage",
      "financeInstruments.manage",
      "financeTransactions.manage",
      "finance.audit.read",
    ],
    legacyRoles: [],
  },
  {
    key: "accountant",
    name: "Mali Müşavir",
    description: "Finans raporlarını salt okunur görür ve muhasebe export paketi indirir.",
    permissions: [
      "admin.access",
      "documents.read",
      "incomingInvoices.read",
      "incomingInvoices.manage",
      "finance.read",
      "financePayables.read",
      "financeReceivables.read",
      "financeReports.read",
      "financeTrialBalance.read",
      "financeLedgerEntries.read",
      "financeAccounts.read",
      "finance.audit.read",
    ],
    legacyRoles: [],
  },
  {
    key: "catalog-manager",
    name: "Katalog Yöneticisi",
    description: "Ürün, kategori, marka ve vitrin katalog süreçlerini yönetir.",
    permissions: [
      "admin.access",
      "products.read",
      "products.manage",
      "productQuestions.read",
      "productQuestions.manage",
      "categories.manage",
      "storefront.manage",
      "productAttributes.manage",
      "brands.manage",
      "inventory.read",
      "inventoryProducts.read",
      "inventoryTransactions.read",
      "inventoryExports.read",
      "inventoryExternalEvents.read",
      "integrations.read",
    ],
    legacyRoles: [],
  },
  {
    key: "integration-manager",
    name: "Entegrasyon Yöneticisi",
    description: "Pazaryeri ve dış sistem bağlantılarını yönetir.",
    permissions: [
      "admin.access",
      "products.read",
      "productQuestions.read",
      "orders.read",
      "ordersShippingReport.read",
      "inventory.read",
      "inventoryProducts.read",
      "inventoryTransactions.read",
      "inventoryExports.read",
      "inventoryExternalEvents.read",
      "integrations.read",
      "integrations.manage",
      "integrationsTrendyol.manage",
      "integrationsN11.manage",
      "integrationsPazarama.manage",
      "integrationsHepsiburada.manage",
    ],
    legacyRoles: [],
  },
] as const;

export type RbacRoleSummary = {
  id: string;
  key: string;
  name: string;
  description: string | null;
  isSystem: boolean;
  isActive: boolean;
  permissionKeys: string[];
  userCount: number;
};

export type EffectiveRbac = {
  roleKeys: string[];
  roleNames: string[];
  permissionKeys: PermissionKey[];
};
